# Site settings
title: From Founder to Developer
header-img: img/home-bg.png
email: skinnerpa86@yahoo.com
copyright_name: petitlapin86
description: > # this means to ignore newlines until "baseurl:"
  Why I'm climbing "down" the ladder. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  petitlapin86
learn_profile: petitlapin86
email_username: skinnerpa86@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
